name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: my-step
        run: |
          cat <<EOT >> patch.conf
          apiVersion: score.dev/v1b1

          containers:
            app:
              command:
                - /root/.local/bin/fastapi
              args:
                - run
                - /app/main.py
              files:
                - target: /app/index.html
                  content: |
                    $(awk '{print "          " $0}' ${{ github.workspace }}/index.html)
          EOT
          cat patch.conf
